## Grupp4

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns   
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split, GridSearchCV

# Ladda data
df = pd.read_csv('data/historical_data.csv')

In [3]:
print(df.info())
display(df.head())
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          12000 non-null  int64
 1   day                         12000 non-null  int64
 2   event_type                  12000 non-null  str
 3   category                    12000 non-null  str
 4   region                      11660 non-null  str
 5   device                      12000 non-null  str
 6   account_age_days            12000 non-null  float64
 7   num_prev_listings           12000 non-null  int64
 8   prev_reports_30d            12000 non-null  int64
 9   verification_level          12000 non-null  int64
 10  price                       11182 non-null  float64
 11  num_images                  12000 non-null  int64
 12  message_length              12000 non-null  int64
 13  contains_off_platform       12000 non-null  int64
 14  urgency_words               12000 non-null  int64
 15  payment_attempt             12000 non-null  int64
 16  time_to_first_response_min  11410 non-null  float64
 17  is_suspicious               12000 non-null  int64
dtypes: float64(3), int64(11), str(4)
memory usage: 1.6 MB
None

,id,day,event_type,category,region,device,account_age_days,num_prev_listings,prev_reports_30d,verification_level,price,num_images,message_length,contains_off_platform,urgency_words,payment_attempt,time_to_first_response_min,is_suspicious
0,0,8,ad_post,other,urban,android,38.4,2,1,1,594.16,3,91,0,1,0,2.3,0
1,1,4,ad_post,fashion,urban,android,20.0,1,0,1,134.47,2,150,0,0,0,13.6,0
2,2,4,ad_post,other,metro,ios,46.7,3,1,1,198.52,3,72,0,0,0,4.2,0
3,3,3,ad_post,furniture,metro,android,44.3,3,1,2,141.20,3,0,0,0,0,19.8,0
4,4,1,ad_post,electronics,metro,web,211.2,5,0,0,81.39,3,9,0,0,1,23.3,0

,id,day,account_age_days,num_prev_listings,prev_reports_30d,verification_level,price,num_images,message_length,contains_off_platform,urgency_words,payment_attempt,time_to_first_response_min,is_suspicious
count,12000.00000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,11182.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,11410.000000,12000.000000
mean,5999.50000,7.482667,99.632567,3.027750,0.151500,0.710167,207.348603,2.870417,111.154417,0.072833,0.099083,0.181167,22.160438,0.102000
std,3464.24595,4.032520,112.903541,1.766467,0.386083,0.719171,196.226023,1.766886,66.396885,0.259874,0.298786,0.385172,28.834047,0.302661
min,0.00000,1.000000,2.200000,0.000000,0.000000,0.000000,7.670000,0.000000,0.000000,0.000000,0.000000,0.000000,0.300000,0.000000
25%,2999.75000,4.000000,36.300000,2.000000,0.000000,0.000000,86.195000,2.000000,63.000000,0.000000,0.000000,0.000000,6.700000,0.000000
50%,5999.50000,7.000000,66.600000,3.000000,0.000000,1.000000,149.225000,3.000000,108.000000,0.000000,0.000000,0.000000,13.400000,0.000000
75%,8999.25000,11.000000,120.700000,4.000000,0.000000,1.000000,256.795000,4.000000,155.000000,0.000000,0.000000,0.000000,26.600000,0.000000
max,11999.00000,14.000000,2741.700000,12.000000,3.000000,2.000000,2743.080000,10.000000,416.000000,1.000000,1.000000,1.000000,579.800000,1.000000

## Pipeline

In [4]:
target_name = "is_suspicious"
X = df.drop(columns=[target_name])
y = df[target_name]

# make numeric/category feature
numeric_features = X.select_dtypes(include=["number"]).columns.tolist()
categorical_features = X.select_dtypes(include=["string"]).columns.tolist()


X_train, X_test, y_train, y_test = train_test_split(
    X,y,
    test_size=0.30,
    random_state=42,
    stratify=y
)
# print("X_Train : ", X_train.shape, "X_Test : ", X_test.shape)
# print(f"\n{target_name} is important to have no missing values")
# print("\nMissing Values (train)")
# print(X_train.isna().sum().sort_values(ascending=False).head(10))
# print("\nMissing Values (test)")
# print(X_test.isna().sum().sort_values(ascending=False).head(10))
print("numeric_features :", numeric_features)
print("\ncategorical_features :", categorical_features)

numeric_features : ['id', 'day', 'account_age_days', 'num_prev_listings', 'prev_reports_30d', 'verification_level', 'price', 'num_images', 'message_length', 'contains_off_platform', 'urgency_words', 'payment_attempt', 'time_to_first_response_min']

categorical_features : ['event_type', 'category', 'region', 'device']

## Pipeline

In [5]:



numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=False
    ))
])

preprocess = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)

    ],
    remainder="drop"
)

In [ ]:
#Test Area: